### ISSUE TITLE
messages using top-level defined enums pick the wrong library name

### ISSUE THREAD

**Issue by lightyear15** [datachainlab/solidity-protobuf#11]
Here it's a protobuf test
```proto
syntax = "proto3";

package test;

enum ThisIsAnEnum {
    Nothing = 0;
    Something = 1;
    Anything = 2;
}

message ThisIsAMessage {
    string text = 1;
    ThisIsAnEnum content = 2;
}
```
running
```bash
$ ./run.sh --input test.proto --output .
```
the global-level enum is include in
```solidity
library TEST_PROTO_GLOBAL_ENUMS {

  //enum definition
  // Solidity enum definitions
  enum ThisIsAnEnum {
    Nothing,
    Something,
    Anything
  }
...
```
However the generated code for the message is
```solidity
library TestThisIsAMessage {


  //struct definition
  struct Data {
    string text;
    test.ThisIsAnEnum content;
  }
...
```
You can see that ``Data`` is looking for the enum in the wrong library. ``test`` library does not exist

**Comment by siburu** [comment]
@lightyear15 I believe that it is relatively easy to fix the code generator as follows, but does it match your needs?

### Current
```
  struct Data {
    string text;
    test.ThisIsAnEnum content;
  }
```

### Revised
```
  struct Data {
    string text;
    TEST_PROTO_GLOBAL_ENUMS.ThisIsAnEnum content;
  }
```

**Comment by lightyear15** [comment]
> @lightyear15 I believe that it is relatively easy to fix the code generator as follows, but does it match your needs?
> ### Current
> 
> ```
>   struct Data {
>     string text;
>     test.ThisIsAnEnum content;
>   }
> ```
> 
> ### Revised
> 
> ```
>   struct Data {
>     string text;
>     TEST_PROTO_GLOBAL_ENUMS.ThisIsAnEnum content;
>   }
> ```

Yes, as long as the code compiles it's fine to me.
