### ISSUE TITLE
ProtobufRuntime issue, possibly when decoding array of int32

### ISSUE THREAD

**Issue by lightyear15** [datachainlab/solidity-protobuf#23]
Please refer to the bug reported in repository:
https://github.com/lightyear15/sol-protobug

As explained in the README, it looks like it might be something related to the [``repeated int32``](https://github.com/lightyear15/sol-protobug/blob/88fa62ae14b768c5f1d634cdcce887354392ccfd/test.proto#L57) field.

**Comment by siburu** [comment]
Thanks for this report!
I investigated this issue and finally noticed that the current implementation of `solidity-protobuf` cannot decode packed repeated fields at all.
In proto3, repeated fields of scalar numeric types are packed by default.

(For packed repeated fields, see https://developers.google.com/protocol-buffers/docs/encoding#packed)

**Comment by siburu** [comment]
In fact, I passed your test by adding `[packed=true]` to L57.
https://github.com/lightyear15/sol-protobug/blob/main/test.proto#L57

**Comment by siburu** [comment]
@lightyear15 This is still an issue and should be fixed at some point, but can you use this workaround (`[packed=false]`) at this point?

**Comment by lightyear15** [comment]
Thanks a lot @siburu ,
The protobuf message definition are not under my control.
I can try to push for review the change and see what maintainers have to say about.
In the meantime: thanks a lot
