### ISSUE TITLE
Allow use an external runtime library

### ISSUE THREAD

**Issue by bluele** [datachainlab/solidity-protobuf#4]
This should be implemented as a generator option.

**Comment by siburu** [comment]
To elaborate on this, in the current implementation, `solidity-protobuf` runtime libraries (ProtoBufRuntime.sol and GoogleProtobufAny.sol) are necessarily generated to a output directory and all other .sol files have hard-coded import paths of them like `import "./ProtoBufRuntime.sol"`.
We should make it more flexible.
